config/routes.rb
Testsite::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy, :gmap]
  resources :friendships, only: [:create, :update, :destroy, :index]
  resources :maps, only: :show
  resources :comments

  match '/home',     to: 'static_pages#home'
  match '/help',     to: 'static_pages#help'
  match '/about',    to: 'static_pages#about'
  match '/contact',  to: 'static_pages#contact'
  
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete
  
  match '/friendships/:id', to: 'friendships#create', via: :post
  

  root :to => 'static_pages#home'

end

app/views/shared/_comment.html.erb
<li id="c<%= comment.id %>">
<%= link_to (gravatar_for comment.user, size: 32), comment.user %>
<span class="user">
  <%= link_to comment.user.name, comment.user %>
</span>
<span class="content">
<%= wrap(comment.content) %>
</span>
<span class="timestamp">
  Posted <%= time_ago_in_words(comment.created_at) %> ago.
</span>

<% if current_user?(comment.user) %>
    <%= link_to raw('<i class="icon-trash icon-black"></i>'),
                                      comment, method: :delete,
                                      data: { confirm: "Are you sure?" },
                                      remote: true,
                                      title: "Delete comment" %>
<% end %>
</li>

app/views/shared/_comment_form.erb
<%= gravatar_for current_user, size:24 %>
<%= form_for(post.comments.build, remote: true) do |f| %>
  <%= f.text_field :content, :placeholder => 'Comment', class: "span7" %>
  <%= f.hidden_field :post_id, :value => post.id%>
  <input  type="submit" name="post" value="post" 
    style="position: absolute; height: 0px; width: 0px; border: none; padding: 0px;"
    hidefocus="true" tabindex="-1"/>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <% if msg == "Password digest can't be blank" %>
        <% next %>
      <% else %>
        <li>* <%= msg %></li>
      <% end %>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class ="posts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user, class: "gravatar" %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  <span class="content"><%= wrap(feed_item.content) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago 
    <% if !(feed_item.state.nil? && feed_item.city.nil?) %>
    <%= link_to "from #{feed_item.city}, #{feed_item.state}.", map_path(feed_item.id, act: "show"),
                                                              remote: true,
                                                              title: "show map"%>
    <% end %>
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to raw('<i class="icon-trash icon-black"></i>'),
                                      feed_item, method: :delete,
                                      data: { confirm: "Are you sure?" },
                                      remote: true,
                                      title: "Delete post" %>
  <% end %>
  <div id="gmap">
  </div>



<ul class="indent">
  <% if feed_item.comments.any? %>
  <%= render partial: 'shared/comment', collection: feed_item.comments %>
  <% end %>
  <li>
    <%= render partial: 'shared/comment_form', locals: {post: feed_item} %>
  </li>

</ul>


</li>

app/views/shared/_post_form.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-custom" %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post, remote: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-custom" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span id="postcount">
  <%= pluralize(current_user.posts.count, "post") %>
</span>