config/routes.rb
Testsite::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy, :gmap]
  resources :friendships, only: [:create, :update, :destroy, :index]
  resources :maps, only: :show
  resources :comments

  match '/home',     to: 'static_pages#home'
  match '/help',     to: 'static_pages#help'
  match '/about',    to: 'static_pages#about'
  match '/contact',  to: 'static_pages#contact'
  
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete
  
  match '/friendships/:id', to: 'friendships#create', via: :post
  

  root :to => 'static_pages#home'

end

app/models/friendship.rb
# == Schema Information
#
# Table name: friendships
#
#  id            :integer          not null, primary key
#  friendable_id :integer
#  friend_id     :integer
#  blocker_id    :integer
#  pending       :boolean          default(TRUE)
#

class Friendship < ActiveRecord::Base

  belongs_to :user


end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  #before_filter
  
  def show
  end
  
  def index
    @friends = current_user.friends
    @pag_friends = current_user.friends.paginate(page: params[:page], per_page: 3)
    @pending_invited_by = current_user.pending_invited_by
    @pending_invited = current_user.pending_invited
  end
  
  def create
    @Friend = User.find(params[:id])
    @friendship_created = current_user.invite(@Friend)
    @pending_invited_by = current_user.pending_invited_by
    if @friendship_created
      flash[:notice] = "Friend invitation sent to #{@Friend.name}"
      redirect_to @Friend
    end
  end
    
  def update
    @update_param = params[:foo]
    @pag_friends = current_user.friends.paginate(page: params[:page], per_page: 3)
    @friends = current_user.friends
    @friend_id = params[:id]
    @Friend = User.find(@friend_id)
    @friendship_approved = current_user.approve(@Friend)
    if @update_param == 'decline'
      #Can't do anything about this, this is how you decline
      current_user.remove_friendship(@Friend)
    end
    @pending_invited_by = current_user.pending_invited_by #pending array
    respond_to do |format|
      format.html {redirect_to friendships_url}
      format.js
    end
  end
  
  def destroy
    @friends = current_user.friends
    #@page_path = /(.*?)\d*$/.match(params[:page])[1]
    @pag_friends = current_user.friends.paginate(page: params[:page], per_page: 3)
    @Friend = User.find(params[:id])
    @friendship = current_user.send(:find_any_friendship_with, @Friend)
    if @friendship
      @friendship.delete
      @removed = true
      respond_to do |format|
        format.html {redirect_to friendships_url}
        format.js
      end
    end
  end
  
end
  

app/helpers/friendships_helper.rb
module FriendshipsHelper

end

app/views/friendships/_friends.html.erb
      <% if @friends.any? %>
        <%= will_paginate @pag_friends %>
        <ul class="users">
          <%= render partial: 'pag_friends', collection: @pag_friends, as: :friend %>
        </ul>
        <%= will_paginate @pag_friends %>
      <% else %>
        <p>No friends yet</p>
      <% end %>

app/views/friendships/_pag_friends.html.erb
<li>
  <%= gravatar_for friend, size: 52 %>
  <%= link_to friend.name, friend %>
  | <%= link_to "defriend", friendship_path(friend.id), method: :delete,
                                  remote: true,
                                  data: { confirm: "You sure?" } %>

</li>

app/views/friendships/_pending_invited_by.erb
<li id=pending_<%= friend.id %>>
  <%= gravatar_for friend, size: 26 %>
  <%= link_to friend.name, friend %>
  | <%= link_to "Accept", friendship_path(id: friend.id, foo: "approve"),
                                method: :put,
                                class: "accept",
                                remote: true %>
  | <%= link_to "Decline", friendship_path(id: friend.id, foo: "decline"),
                                method: :put,
                                class: "decline",
                                remote: true %>
</li>

app/views/friendships/destroy.js.erb
$("#friend_list").html(
                        "<%= escape_javascript(render( partial: 'friends',
                        locals: {friends: @friends, pag_friends: @pag_friends})) %>");

$(".pagination a").attr('href', function(){
return this.href.replace(/friendships\/\d+/, 'friendships');
});




app/views/friendships/index.html.erb
<% provide(:title, "Friend index") %>

<div class="row">

<% if @pending_invited_by.any? %>
  <aside class="span4" id="invited_aside">
      <section>
        <h2>Pending requests</h2>
      </section>
      <section>
        <ul class="invited_by" id="pending_invited">
          <%= render partial: 'pending_invited_by', collection: @pending_invited_by, as: :friend %>
        </ul>
      </section>
  </aside>
<% end %>
  
  <div class="span8">
    <h1>
      Friends
    </h1>
    <div id="friend_list">
      <%= render partial: 'friends', locals: {friends: @friends, pag_friends: @pag_friends} %>
    </div>
  </div>
</div>

app/views/friendships/update.js.erb

$("#pending_<%= @friend_id %>").remove();
<% if @update_param == 'approve' %>
  $("#friend_list").html(
                        "<%= escape_javascript(render( partial: 'friends',
                        locals: {friends: @friends, pag_friends: @pag_friends})) %>");
<%end %>
<% if @pending_invited_by.empty? %>
  $("#invited_aside").fadeOut(1000);
<% end %>

$(".pagination a").attr('href', function(){
return this.href.replace(/friendships\/\d+/, 'friendships');
});